services:
  web:
    build: ./server
    container_name: workshop_web
    ports:
      - "8080:80"
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db

  client:
    build: ./client
    container_name: workshop_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - api

  db:
    image: mysql:8.0
    container_name: workshop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workshop_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    container_name: workshop_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  api:
    build: ./laravel
    container_name: workshop_api
    volumes:
      - ./laravel:/var/www
      - vendor:/var/www/vendor        # vendor stocke cote Linux (rapide)
    environment:
      PHP_CLI_SERVER_WORKERS: 4       # 4 requetes en parallele
    command: sh -c "composer install --no-interaction && php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
  vendor: